# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Mod Properties
mod_version=1.21.11-1.5.2
maven_group=cutefox.betterenchanting
archives_base_name=betterenchanting

# Dependencies
fabric_version=0.141.3+1.21.11
#bublezone_version_id=oNmsCcuk
#horseshoes_version_id=kkbe6Z5v
enderscape_version_id=3cYKvu3m
#spell_engine_version=1.1.2+1.21.1
midnightlib_version = OeTayxh3
modmenu_version=17.0.0-beta.2
